<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>php</string>
	</array>
	<key>injectionSelector</key>
	<string>L:text.html -source.php</string>
	<key>name</key>
	<string>Automad</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#content</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#statements</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\&lt;#</string>
					<key>end</key>
					<string>#\&gt;</string>
					<key>name</key>
					<string>comment.block.automad</string>
				</dict>
			</array>
		</dict>
		<key>content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>@\{</string>
					<key>contentName</key>
					<string>variable.other.automad</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>variable.other.automad</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#pipe</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\b(and|else|end|for|foreach|if|in|next|not|or|prev|snippet|to|with)\b|[\&lt;\&gt;\=]+)</string>
					<key>name</key>
					<string>keyword.other.automad</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d[\d\.]*\b</string>
					<key>name</key>
					<string>support.constant.automad</string>
				</dict>
			</array>
		</dict>
		<key>options</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>contentName</key>
					<string>entity.other.attribute-name.automad</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>entity.other.attribute-name.automad</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#content</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>pipe</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\|)\s*[\+\-\*\/]\s*[\w\-\.]+</string>
					<key>name</key>
					<string>entity.other.attribute-name.automad</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.control.automad</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>contentName</key>
					<string>keyword.other.automad</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>keyword.control.automad</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\&lt;@</string>
					<key>contentName</key>
					<string>support.type.automad</string>
					<key>end</key>
					<string>@\&gt;</string>
					<key>name</key>
					<string>keyword.control.automad</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#content</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#options</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>contentName</key>
					<string>string.automad</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.automad</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#content</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>contentName</key>
					<string>string.automad</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.automad</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#content</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.automad</string>
	<key>uuid</key>
	<string>4B56EAFE-83D8-4CC4-B849-9489E77E0313</string>
</dict>
</plist>
